import { zodToJsonSchema } from "zod-to-json-schema";
import { documentSchema } from "./document";
import { blockGuide } from "./blocks/registry";
import { VERSION } from "./version";

/** The JSON Schema the agent should author against (and the CLI validates against). */
export function jsonSchema(): object {
  return zodToJsonSchema(documentSchema, { name: "ChangeProposalDocument" });
}

/**
 * The full authoring guide emitted by `change-proposal author`. This is the versioned
 * contract — the thin skill fetches it at runtime, so it can never drift from the tool.
 */
export function authoringGuide(): string {
  return [
    `# Change Proposal — authoring guide (v${VERSION})`,
    "",
    '(For describing the CURRENT state of a system instead of proposing a change, use the sibling tool `describe-architecture` — same file format, `kind: "architecture-description"`.)',
    "",
    "You are producing a `proposal.json` for a human to review interactively instead of",
    "reading a markdown plan. Break the change into sections the human can approve one by one.",
    "",
    "## Writing it — altitude and language",
    "The reviewer is the product owner, not the code's author. Every line either helps them",
    "decide something or spends their attention for nothing.",
    "",
    "- **A section is a decision surface.** Before adding one, name the decision it carries.",
    "  If nothing the reviewer could say would change what you do, it is not a section — it is",
    "  one line of context inside another section. A proposal whose every section can only be",
    "  approved is documentation, not a proposal. Most changes fit in 3–7 sections.",
    "- **Budget detail by cost-of-being-wrong.** Hard-to-reverse things — migrations, API",
    "  contracts, data handling, security — get the diffs, diagrams, and tables. Easily",
    "  changed internals (naming, private module layout) get a summary line at most.",
    "- **Route real decisions to input surfaces.** A decision buried in prose gets skimmed",
    "  past; a `conflict` field or choice question with trade-off notes gets answered.",
    "- **Titles and summaries say what changes, for whom, in plain words** — \"Fix: importing",
    "  from Google Tasks overwrites your local edits\", not \"3-way merge refactor\". Write each",
    "  `summary` for someone who never expands the card. Open each section body with the",
    "  one-sentence \"so what\"; evidence after. No unexplained jargon.",
    "- **Trim before sending.** A Tests section listing fifteen test names is noise; one",
    "  callout — \"placement core is pure; golden tests pin contention, pins, DST\" — is",
    "  signal. Cut the block you are least sure earns its place.",
    "",
    "## Rules",
    `- Set \`version\` to exactly \`"${VERSION}"\`. A mismatch is rejected (no fallbacks).`,
    "- Set `status` to `\"pending\"` and `round` to `1` for a first review.",
    "- Leave `response` empty (or omit it) — the human fills it in.",
    "- Author the `proposal` region only. It is read-only to the human.",
    "- The schema is strict: no extra keys, and every block `type` must be a known block.",
    "",
    "## Document shape",
    "```",
    "{",
    '  "version": "' + VERSION + '",',
    '  "status": "pending",',
    '  "round": 1,',
    '  "proposal": {',
    '    "title": "Fix: importing from Google Tasks overwrites your local edits",',
    '    "description": "One-paragraph summary (Markdown).",',
    '    "sections": [ /* see below */ ],',
    '    "questions": [ /* optional */ ]',
    "  }",
    "}",
    "```",
    "",
    "## Sections",
    "Each section is a card the human approves/rejects/comments on. Author-defined — use",
    "whatever sections fit the change (schema, logic, code, api, tests, docs, rollout, …).",
    "- `id`: stable unique string.",
    "- `title`: short heading.",
    "- `badge`: optional short mono label (`DB`, `API`).",
    "- `accent`: `blue | green | red | amber | violet | neutral` — styling only.",
    "- `summary`: optional one-line summary.",
    "- `blocks`: ordered content blocks (below).",
    "",
    "## Blocks",
    blockGuide(),
    "",
    "## Questions (optional)",
    "Ask the human for decisions. `kind: 'choice'` with `options: [{id,label}]` (set",
    "`allowOther: true` to offer a write-in), or `kind: 'text'` for free-form answers.",
    "",
    "## Dialog (the per-section conversation)",
    "`dialog` is a shared, cross-round thread keyed by section id. The human appends notes",
    "via the UI; you append replies by adding entries with `author: \"agent\"`. Entries carry",
    "the `round` they were written in and are never wiped — a section reads as one",
    "conversation across the whole review. Leave `dialog: {}` on a first-round proposal.",
    "",
    "## Iterating (round 2+)",
    "Don't hand-reset the response. Run `change-proposal iterate <file>` — it archives the",
    "current `response` into `history`, resets the live response, keeps the `dialog`, and",
    "bumps `round`. Then revise the `proposal`, optionally add `author: \"agent\"` dialog",
    "replies to sections you changed, and run `review` again.",
    "",
    "## Reading the result",
    "`review` prints an agent-readable digest when it returns, and `change-proposal result",
    "<file>` re-prints it anytime: outcome, verdicts, conflict picks, and answers with every",
    "id joined back to its label. Prefer the digest; read the raw JSON only for something it",
    "omits. What the fields mean:",
    "",
    "When the human finalizes, `status` becomes `finalized`. Read `response.outcome` FIRST —",
    "it is the overall intent, and per-section verdicts are optional detail beneath it:",
    "- `\"approved\"` → they agree. Go ahead with whatever THIS proposal was gating. That is",
    "  not automatically \"write code now\" — depending on what you proposed it may mean draft",
    "  the full plan, run the migration, etc. Decide the next step from the proposal's content.",
    "- `\"discuss\"` → do NOT go ahead. Reply in the `dialog` on the sections in question,",
    "  run `iterate`, and send back another round.",
    "Then read `response.review` (per-section verdicts), the `dialog` thread, and answers.",
    "If you authored any `conflict` blocks, read `response.resolutions` — keyed",
    "`\"<blockId>.<fieldId>\"` to `{ side, text? }` (`side` is a chosen side id, or `\"__other__\"`",
    "with a `text` write-in). A field may be unresolved (the human left it for you to decide).",
    "",
    "## After authoring",
    "Write the JSON to a file, then run `change-proposal review <file>`.",
    "",
    "## JSON Schema",
    "```json",
    JSON.stringify(jsonSchema(), null, 2),
    "```",
  ].join("\n");
}

/**
 * The authoring guide emitted by `describe-architecture author`. Same file format and
 * versioned contract as change-proposal; a different kind with a different loop: the
 * agent describes the CURRENT system, the human confirms or asks for clarification.
 */
export function describeGuide(): string {
  return [
    `# Describe Architecture — authoring guide (v${VERSION})`,
    "",
    "You are producing an `architecture.json` that presents your understanding of the",
    "CURRENT state of a system — architecture, data model, app state, APIs — as an",
    "interactive page instead of a markdown writeup. The human does not approve a change;",
    "they run a **clarification loop**: each section is marked `clear` or",
    "`needs-clarification`, and you answer the clarification requests in another round.",
    "This is how you and the human converge on a shared, verified mental model before",
    "any work is planned against it.",
    "",
    "## Rules",
    `- Set \`version\` to exactly \`"${VERSION}"\`. A mismatch is rejected (no fallbacks).`,
    '- Set `kind` to `"architecture-description"`. (The change-proposal verdict/outcome',
    "  tokens are invalid for this kind, and vice versa — hard-checked.)",
    '- Set `status` to `"pending"` and `round` to `1` for a first description.',
    "- Leave `response` empty (or omit it) — the human fills it in.",
    "- Describe what IS, not what should be. Leave block `status` markers",
    "  (`added`/`modified`/`removed`) off unless you are flagging in-flight work.",
    "- Say where you are unsure. Uncertainty belongs in `questions` — asking the human to",
    "  confirm beats presenting a guess as fact.",
    "",
    "## Document shape",
    "```",
    "{",
    '  "version": "' + VERSION + '",',
    '  "kind": "architecture-description",',
    '  "status": "pending",',
    '  "round": 1,',
    '  "proposal": {',
    '    "title": "How task-app works today",',
    '    "description": "One-paragraph summary (Markdown).",',
    '    "sections": [ /* see below */ ],',
    '    "questions": [ /* things you need the human to confirm */ ]',
    "  }",
    "}",
    "```",
    "",
    "## Sections",
    "Each section is a card the human marks clear / asks to clarify. Author-defined — use",
    "whatever cuts fit the system (overview, architecture, data model, state & lifecycle,",
    "APIs, integrations, deployment, …).",
    "- `id`: stable unique string.",
    "- `title`: short heading.",
    "- `badge`: optional short mono label (`ARCH`, `DB`, `STATE`).",
    "- `accent`: `blue | green | red | amber | violet | neutral` — styling only.",
    "- `summary`: optional one-line summary.",
    "- `blocks`: ordered content blocks (below). For structure use `arch-flow` /",
    "  `arch-layers` / `arch-boundaries`; for the data model use `er`; for prose use",
    "  `markdown`; for known gaps or sharp edges use `callout`.",
    "",
    "## Blocks",
    blockGuide(),
    "",
    "## Questions (optional)",
    "Ask the human to confirm what you could not verify from the code. `kind: 'choice'`",
    "with `options: [{id,label}]` (set `allowOther: true` for a write-in), or",
    "`kind: 'text'` for free-form answers.",
    "",
    "## Dialog (the per-section conversation)",
    "`dialog` is a shared, cross-round thread keyed by section id. The human's",
    "clarification requests land here; you answer by adding entries with",
    '`author: "agent"` when authoring the next round. Leave `dialog: {}` on round 1.',
    "",
    "## Iterating (round 2+)",
    "Don't hand-reset the response. Run `describe-architecture iterate <file>` — it",
    "archives the current `response` into `history`, resets the live response, keeps the",
    "`dialog`, and bumps `round`. Then clarify/expand the sections that were flagged,",
    'reply in `dialog` with `author: "agent"` entries, and run `review` again.',
    "",
    "## Reading the result",
    "`review` prints an agent-readable digest when it returns, and `describe-architecture",
    "result <file>` re-prints it anytime: outcome, verdicts, and answers with every id",
    "joined back to its label. Prefer the digest; read the raw JSON only for something it",
    "omits. What the fields mean:",
    "",
    "When the human finalizes, `status` becomes `finalized`. Read `response.outcome` FIRST:",
    '- `"understood"` → the description landed. Treat it as shared, human-verified context',
    "  for whatever comes next.",
    '- `"clarify"` → sections marked `needs-clarification` (see `response.review`) need',
    "  expanding. Read their `dialog` threads for the actual questions, answer them, run",
    "  `iterate`, and present another round.",
    "Then read `response.answers` (your questions) and `response.feedback` (global note).",
    "",
    "## After authoring",
    "Write the JSON to a file, then run `describe-architecture review <file>`.",
    "",
    "## JSON Schema",
    "```json",
    JSON.stringify(jsonSchema(), null, 2),
    "```",
  ].join("\n");
}
